Mode run report logic
shipyardapp/mode-blueprints pull request #1
Opened 2022-07-12 20:31 UTC by Shamwayne

Token run report functionality

For Authentication details: https://mode.com/developer/api-reference/authentication/
note **token_id** and **token_password** were used instead of **username** and **password** for clarity's sake

2022-07-21 23:03 UTC, blakeburch requested changes
Overall, good. Just minor adjustments needed.

2022-07-21 23:03 UTC, blakeburch commented on mode_blueprints/run_report.py
> +        print("Run report for ID: {report_id} successful")
Can we adjust to `Run report for ID: {report_id} was successfully triggered.` just to clarify a bit more that the run was triggered, but that doesn't mean it was successful.

2022-08-12 15:16 UTC, blakeburch approved these changes

2022-08-12 15:27 UTC, blakeburch approved these changes

2022-08-12 17:09 UTC, ericelsken approved these changes

2022-08-13 21:54 UTC, merged