Sc 3336/mode download report as file
shipyardapp/mode-blueprints pull request #3
Opened 2022-07-12 21:51 UTC by Shamwayne

2022-07-22 00:20 UTC, blakeburch requested changes
I couldn't get this to run, due to `Mode run report returned an unknown status 400/n returned data: {"id":"bad_request","message":"request path not recognized","_links":{"help":{"href":"https://mode.com/help"}}}`

2022-08-03 00:08 UTC, Shamwayne commented
@blakeburch

2022-08-12 15:06 UTC, blakeburch approved these changes

2022-08-12 17:13 UTC, ericelsken approved these changes

2022-08-13 22:00 UTC, blakeburch approved these changes

2022-08-13 22:00 UTC, merged